// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz2vtbpENy-yziBneeXpWCRH_k4oVq5d4',
    appId: '1:29587097783:web:52b0328aa4c26b5d9b6532',
    messagingSenderId: '29587097783',
    projectId: 'pdf-payment-app-devaj',
    authDomain: 'pdf-payment-app-devaj.firebaseapp.com',
    storageBucket: 'pdf-payment-app-devaj.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJpaiE3jPb4AU7n_9im3Gge4Lg6vP1XtE',
    appId: '1:29587097783:android:5dd26d7b8ade05ea9b6532',
    messagingSenderId: '29587097783',
    projectId: 'pdf-payment-app-devaj',
    storageBucket: 'pdf-payment-app-devaj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCasxahAMn6UU6uxJ3w6fembBz-4QZ9Mzo',
    appId: '1:29587097783:ios:e69253bafd80ea319b6532',
    messagingSenderId: '29587097783',
    projectId: 'pdf-payment-app-devaj',
    storageBucket: 'pdf-payment-app-devaj.firebasestorage.app',
    iosBundleId: 'com.example.pdfViewer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCasxahAMn6UU6uxJ3w6fembBz-4QZ9Mzo',
    appId: '1:29587097783:ios:e69253bafd80ea319b6532',
    messagingSenderId: '29587097783',
    projectId: 'pdf-payment-app-devaj',
    storageBucket: 'pdf-payment-app-devaj.firebasestorage.app',
    iosBundleId: 'com.example.pdfViewer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz2vtbpENy-yziBneeXpWCRH_k4oVq5d4',
    appId: '1:29587097783:web:dd9687f91d2316489b6532',
    messagingSenderId: '29587097783',
    projectId: 'pdf-payment-app-devaj',
    authDomain: 'pdf-payment-app-devaj.firebaseapp.com',
    storageBucket: 'pdf-payment-app-devaj.firebasestorage.app',
  );
}
